# These are supported funding model platforms

github: Artifact-Virtual 
patreon:
open_collective: hektor
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:
custom:
  - 'bitcoin:14Npja986ZQJDVkAdqigLQhoLkfRyfbsgL'
  - 'https://www.binance.com' # replace with a specific donation link if desired
  - 'arcmarketing.cb.id'
  - 'ethereum:0xC06fD1dA15a5757a812aF20eB330E129f0a7D611'
  - 'base:0xdb3c3f9ecb93f3532b4fd5b050245dd2f2eec437' # ARCx V2 project funding token
